# Generated by Django 5.0.6 on 2024-07-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_trend'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='Cat', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='contact_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.DecimalField(decimal_places=2, default=4000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Lovely Pet', max_length=255),
        ),
    ]
