# Generated by Django 5.0.6 on 2024-08-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='age',
            field=models.IntegerField(blank=True, help_text='Age in months', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='breed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='health_certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='microchipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='trained',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='vaccinated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True),
        ),
    ]
