# Generated by Django 5.0.6 on 2024-09-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_bookmark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-updated_at', '-created_at')},
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
